In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([ [1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.ndim)

2


In [6]:
print(a.ndim)

1


In [8]:
print(b.shape) # take dimensions

(2, 3)


In [10]:
print(b[1,2]) # take by indexes

6


In [13]:
print(b[1,0:]) # to take 1 row

[4 5 6]


In [14]:
print(b[:,0]) # to take 0 column

[1 4]


In [15]:
b = np.full((2,3),10)
print(b)

[[10 10 10]
 [10 10 10]]


In [16]:
c = np.full_like(b,2)
print(c)

[[2 2 2]
 [2 2 2]]


In [17]:
ident = np.identity(5)
print(ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
a = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [21]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
x = 4


In [1]:
print("Hello world")

Hello world
